import { PERMISSIONS } from '@gemerp/shared';
import { StockDocumentStatus, StockTransactionType } from '@prisma/client';

/**
 * Pure domain rules for stock transaction documents (spec §13,
 * docs/status-transitions.md §2). Kept free of Nest/Prisma clients so the
 * state machine is unit-testable without any infrastructure.
 */

/** How a posted transaction of a given type moves stock. */
export type MovementDirection = 'IN' | 'OUT' | 'MOVE';

/**
 * Direction per type. REVERSAL is intentionally absent: its ledger entries are
 * always the negation of the reversed transaction's entries, never derived
 * from a direction map.
 */
export const TYPE_DIRECTION: Record<
  Exclude<StockTransactionType, 'REVERSAL'>,
  MovementDirection
> = {
  [StockTransactionType.OPENING_BALANCE]: 'IN',
  [StockTransactionType.PURCHASE_RECEIPT]: 'IN',
  [StockTransactionType.NON_PURCHASE_RECEIPT]: 'IN',
  [StockTransactionType.RETURN_FROM_EMPLOYEE]: 'IN',
  [StockTransactionType.INTER_BRANCH_TRANSFER_IN]: 'IN',
  [StockTransactionType.ADJUSTMENT_INCREASE]: 'IN',
  [StockTransactionType.ISSUE_TO_EMPLOYEE]: 'OUT',
  [StockTransactionType.ISSUE_TO_DEPARTMENT]: 'OUT',
  [StockTransactionType.RETURN_TO_SUPPLIER]: 'OUT',
  [StockTransactionType.INTER_BRANCH_TRANSFER_OUT]: 'OUT',
  [StockTransactionType.ADJUSTMENT_DECREASE]: 'OUT',
  [StockTransactionType.MAINTENANCE_ISSUE]: 'OUT',
  [StockTransactionType.DISPOSAL]: 'OUT',
  [StockTransactionType.LOCATION_TRANSFER]: 'MOVE',
};

export function directionOf(
  type: StockTransactionType,
): MovementDirection | null {
  if (type === StockTransactionType.REVERSAL) {
    return null;
  }
  return TYPE_DIRECTION[type];
}

/**
 * Types that can never be created directly through POST /stock-transactions:
 * inter-branch legs are generated by the transfer document flow and reversals
 * by POST /stock-transactions/:id/reverse.
 */
export const SYSTEM_GENERATED_TYPES: readonly StockTransactionType[] = [
  StockTransactionType.INTER_BRANCH_TRANSFER_OUT,
  StockTransactionType.INTER_BRANCH_TRANSFER_IN,
  StockTransactionType.REVERSAL,
];

/**
 * Create/edit permission per transaction type (api-outline 4.1):
 * receipts → inventory.receive, issues → inventory.issue, returns →
 * inventory.return, location transfers → inventory.transfer, adjustments,
 * opening balances & write-offs → inventory.adjust.
 */
export const TYPE_CREATE_PERMISSION: Record<StockTransactionType, string> = {
  [StockTransactionType.OPENING_BALANCE]: PERMISSIONS.inventory.adjust,
  [StockTransactionType.PURCHASE_RECEIPT]: PERMISSIONS.inventory.receive,
  [StockTransactionType.NON_PURCHASE_RECEIPT]: PERMISSIONS.inventory.receive,
  [StockTransactionType.ISSUE_TO_EMPLOYEE]: PERMISSIONS.inventory.issue,
  [StockTransactionType.ISSUE_TO_DEPARTMENT]: PERMISSIONS.inventory.issue,
  [StockTransactionType.MAINTENANCE_ISSUE]: PERMISSIONS.inventory.issue,
  [StockTransactionType.RETURN_FROM_EMPLOYEE]: PERMISSIONS.inventory.return,
  [StockTransactionType.RETURN_TO_SUPPLIER]: PERMISSIONS.inventory.return,
  [StockTransactionType.LOCATION_TRANSFER]: PERMISSIONS.inventory.transfer,
  [StockTransactionType.INTER_BRANCH_TRANSFER_OUT]:
    PERMISSIONS.inventory.transfer,
  [StockTransactionType.INTER_BRANCH_TRANSFER_IN]:
    PERMISSIONS.inventory.transfer,
  [StockTransactionType.ADJUSTMENT_INCREASE]: PERMISSIONS.inventory.adjust,
  [StockTransactionType.ADJUSTMENT_DECREASE]: PERMISSIONS.inventory.adjust,
  [StockTransactionType.DISPOSAL]: PERMISSIONS.inventory.adjust,
  [StockTransactionType.REVERSAL]: PERMISSIONS.inventory.reverse,
};

/** Types whose documents must always carry a reason (spec §25). */
export const REASON_REQUIRED_TYPES: readonly StockTransactionType[] = [
  StockTransactionType.ADJUSTMENT_INCREASE,
  StockTransactionType.ADJUSTMENT_DECREASE,
  StockTransactionType.DISPOSAL,
  StockTransactionType.REVERSAL,
];

/** Stock-document event names (explicit action endpoints, outline 1.8). */
export type StockTransactionEvent =
  | 'update'
  | 'submit'
  | 'approve'
  | 'reject'
  | 'post'
  | 'cancel'
  | 'reverse';

/**
 * from-status → allowed events (docs/status-transitions.md §2).
 * `submit` lands on APPROVED directly when no approval workflow matches
 * (the resolution happens in the service; the transition here only says
 * submit is legal from DRAFT).
 */
const TRANSITIONS: Record<StockDocumentStatus, readonly StockTransactionEvent[]> =
  {
    [StockDocumentStatus.DRAFT]: ['update', 'submit', 'cancel'],
    [StockDocumentStatus.PENDING_APPROVAL]: ['approve', 'reject', 'cancel'],
    [StockDocumentStatus.APPROVED]: ['post', 'cancel'],
    [StockDocumentStatus.REJECTED]: [],
    [StockDocumentStatus.POSTED]: ['reverse'],
    [StockDocumentStatus.CANCELED]: [],
    [StockDocumentStatus.REVERSED]: [],
  };

export function canTransition(
  from: StockDocumentStatus,
  event: StockTransactionEvent,
): boolean {
  return TRANSITIONS[from].includes(event);
}

/** Human-readable transition failure message for the 409 envelope. */
export function transitionError(
  from: StockDocumentStatus,
  event: StockTransactionEvent,
): string {
  const allowed = TRANSITIONS[from];
  return `Cannot ${event} a ${from} stock transaction${
    allowed.length > 0 ? ` (allowed: ${allowed.join(', ')})` : ' (terminal status)'
  }.`;
}
